# 02-03-Exercises
**Description:** List of exercises to train the use of NumPy functions. I will try to do the same command without NumPy to make it clear why these commands are better to use.

In [1]:
# Imports
import numpy as np

___
## Question 1
Create an array of 10 zeros.

In [24]:
# Method 1: Python
np.array([0 for _ in range(0,10)]) # or [0] * 10

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# Method 2: Numpy
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

___
## Question 2
Create an array of 10 ones.

In [23]:
# Method 1: Python
np.array([1 for _ in range(0,10)])  # or [1] * 10

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
# Method 2: Numpy
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

___
## Question 3
Create an array of 10 fives.

In [22]:
# Method 1: Python
np.array([5 for _ in range(0,10)])  # or [5] * 10

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [17]:
# Method 2: Numpy
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

___
## Question 4
Create an array of the integers from 10 to 50 (inclusive on both ends).

In [29]:
# Method 1: Python
np.array([i for i in range(10,51)])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [30]:
# Method 2: Numpy
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

___
## Question 5
Create an array of all the even integers from 10 to 50 (inclusive on both ends).

In [31]:
# Method 1: Python
np.array([i for i in range(10,51,2)])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [32]:
# Method 2: Numpy
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

___
## Question 6
Create a $3\times3$ matrix with values ranging from 0 to 8 (inclusive on both ends).

In [39]:
# Method 1: Python
np.array([[i for i in range(0, 3)],
          [i for i in range(3, 6)],
          [i for i in range(6, 9)]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
# Method 2: Numpy
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

___
## Question 7
Create a $3\times3$ identity matrix, usually called $I_3$.

In [44]:
# Method 1: Python
matrix = [[0] * 3 for _ in range(3)]
for i in range(len(matrix)):
    matrix[i][i] = 1
np.array(matrix)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [48]:
# Method 2: Numpy
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

___
## Question 8
Use NumPy to generate a random number between 0 and 1.

In [49]:
# Method 1: Python
import random

np.array(random.random())

array(0.26342177)

In [50]:
# Method 2: Numpy
np.random.rand(1)

array([0.16778912])

___
## Question 9
Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution.

In [63]:
# Method 1: NumPy
np.array([random.gauss(0,1) for _ in range(25)])

array([-6.52194385e-01,  8.87947399e-01,  1.75284481e-01, -2.12921333e-01,
       -1.85645494e-01, -2.07092501e+00, -1.17334325e+00, -1.37901516e+00,
        6.59359757e-01,  7.34266093e-02, -7.79437891e-02,  9.56138132e-02,
        1.46935185e+00,  1.70646922e+00,  3.28063866e-01,  1.68529762e-03,
        1.04968367e+00,  5.54323078e-01,  5.53648635e-01,  1.16365634e+00,
        3.44663645e-01, -1.83510941e-01, -1.35786686e-02, -3.12268605e-01,
       -1.99502494e+00])

In [64]:
# Method 2: Numpy
np.random.normal(0, 1, size=25)

array([-0.37913914, -1.31292374, -0.94431417, -0.62786466,  0.45313212,
       -0.04376851,  0.20481573,  0.92995598, -0.7915995 ,  1.20954495,
       -1.79867997,  1.35664035, -1.12846555, -2.6141343 ,  0.09826111,
        0.03828119,  0.50183474,  0.53657994, -1.49730437, -3.34841003,
       -0.97674254, -0.2268972 , -0.93041264,  2.13072622,  0.43486728])

___
## Question 10
Create the following matrix:

    array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [78]:
# Method 1: Python
np.array([[i/100 for i in range(1, 11)],
          [i/100 for i in range(11, 21)],
          [i/100 for i in range(21, 31)],
          [i/100 for i in range(31, 41)],
          [i/100 for i in range(41, 51)],
          [i/100 for i in range(51, 61)],
          [i/100 for i in range(61, 71)],
          [i/100 for i in range(71, 81)],
          [i/100 for i in range(81, 91)],
          [i/100 for i in range(91, 101)]
          ])

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [79]:
# Method 2: Numpy
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

___
## Question 11
Create an array of 20 linearly spaced points between 0 and 1 (inclusive on both ends).

In [80]:
# Method 1: Numpy
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

___
## Question 12
Use the value <code>mat</code>, defined in

In [2]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


, to compute the following exercises.

### (a)
Write code that generates the output:

    array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [84]:
# Method 1: Numpy
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

### (b)
Write code that generates the output:

    20

In [85]:
# Method 1: Numpy
mat[3,4]

20

### (c)
Write code that generate the output:

    array([[ 2],
       [ 7],
       [12]])

In [86]:
# Method 1: Numpy
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

### (d)
Write code that generates the output:

    array([21, 22, 23, 24, 25])

In [87]:
# Method 1: Numpy
mat[4]

array([21, 22, 23, 24, 25])

### (e)
Write code that generates the output:

    array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [88]:
# Method 1: Numpy
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### (f)
Compute the sum of all elements of the matrix <code>mat</code>.

In [90]:
# Method 1: Numpy
mat.sum()

325

### (g)
Compute the standard deviation of the matrix <code>mat</code>.

In [91]:
# Method 1: Numpy
mat.std()

7.211102550927978

### (h)
Compute the sum of all the columns of the matrix <code>mat</code>.

In [92]:
# Method 1: Numpy
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

### (i)
Compute the sum of all the columns of the matrix <code>mat</code>.

In [94]:
# Method 1: Numpy
mat.sum(axis = 1)

array([ 15,  40,  65,  90, 115])

___
## Question 13
How to make sure that the random number generate is the same in every code execution?

**Answer**: It is possible to fix the seed. This ensure that we can test out functions that generate random numbers. The following code will always produce

    array([0.37454012, 0.95071431, 0.73199394, 0.59865848])


In [98]:
# Method 1: Numpy
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])